force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Tiers</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cost_Per_Product__mdt/Cost_Per_Product__mdt.object-meta.xml
<CustomObject>
    <description>Lists the cost per calendar month, ATM fee in other currencies and Card Replacement cost for each product and country</description>
    <label>Costs Per Product</label>
    <pluralLabel>Costs Per Products</pluralLabel>
</CustomObject>

force-app/main/default/objects/Cost_Per_Product__mdt/fields/ATM_Fee_in_other_currencies__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee_in_other_currencies__c</fullName>
    <label>ATM Fee in other currencies</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Cost_Per_Product__mdt/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <label>Card Replacement Cost</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cost_Per_Product__mdt/fields/Cost_Per_Calendar_Month__c.field-meta.xml
<CustomField>
    <fullName>Cost_Per_Calendar_Month__c</fullName>
    <label>Cost Per Calendar Month</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cost_Per_Product__mdt/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
                <default>true</default>
                <label>DE</label>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cost_Per_Product__mdt/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Metal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Product_Tiers.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
        <default>true</default>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Metal</fullName>
    </customValue>
    <masterLabel>Product Tiers</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Controller/DisplayProductInfoControllerTest.cls
@IsTest
public with sharing class DisplayProductInfoControllerTest{
    @TestSetup
    static void makeData(){
        //Insert a user and use it to create a case with a contact
        User uu = DataFactory.createTestUser(null);
        insert uu;


        System.runAs(uu){
            Contact c1 = DataFactory.createTestContact('Standard', 'DE');
            insert c1;

            Case case1 = DataFactory.createTestCase(c1);
            insert case1;
        }
    }

    @IsTest
    static void testDisplayProductInfoController(){
        // Get the same user
        User u = [SELECT Id
                  FROM User
                  LIMIT 1];

        System.runAs(u){
            // Get the case and get the cost per product related
            Case cTest = [SELECT Id
                          FROM Case
                          LIMIT 1];

            Test.startTest();
            Cost_Per_Product__mdt cppTest = DisplayProductInfoController.getCostPerProduct(cTest.Id);
            Test.stopTest();

            // Assert the values. For Standard DE, ATM_Fee_in_other_currencies__c = 1.70, Card_Replacement_Cost__c = 6, Cost_Per_Calendar_Month__c = 0, Currency__c = '€', Home_Country__c = 'DE', Product__c = 'Standard'

            Assert.isNotNull(cppTest, 'Cost Per Product should not be null');
            Assert.areEqual(cppTest.Home_Country__c, 'DE', 'Country should be DE');
            Assert.areEqual(cppTest.Product__c, 'Standard', 'Product should be Standard');
            Assert.areEqual(cppTest.Currency__c, '€', 'Currency should be €');
            Assert.areEqual(cppTest.ATM_Fee_in_other_currencies__c, 1.70, 'ATM Fee should be 1.70');
            Assert.areEqual(cppTest.Cost_Per_Calendar_Month__c, 0, 'Cost Per Calendar Month should be 0');
            Assert.areEqual(cppTest.Card_Replacement_Cost__c, 6, 'Card Replacement Cost should be 6');
        }
    }

}