force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Tiers</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cost_Per_Product__mdt/Cost_Per_Product__mdt.object-meta.xml
<CustomObject>
    <description>Lists the cost per calendar month, ATM fee in other currencies and Card Replacement cost for each product and country</description>
    <label>Costs Per Product</label>
    <pluralLabel>Costs Per Products</pluralLabel>
</CustomObject>

force-app/main/default/objects/Cost_Per_Product__mdt/fields/ATM_Fee_in_other_currencies__c.field-meta.xml
<CustomField>
    <fullName>ATM_Fee_in_other_currencies__c</fullName>
    <label>ATM Fee in other currencies</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Cost_Per_Product__mdt/fields/Card_Replacement_Cost__c.field-meta.xml
<CustomField>
    <fullName>Card_Replacement_Cost__c</fullName>
    <label>Card Replacement Cost</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cost_Per_Product__mdt/fields/Cost_Per_Calendar_Month__c.field-meta.xml
<CustomField>
    <fullName>Cost_Per_Calendar_Month__c</fullName>
    <label>Cost Per Calendar Month</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cost_Per_Product__mdt/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
                <default>true</default>
                <label>DE</label>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cost_Per_Product__mdt/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Metal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Product_Tiers.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
        <default>true</default>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Metal</fullName>
    </customValue>
    <masterLabel>Product Tiers</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/WebService/WSContactInformationManager.cls
@RestResource(urlMapping = '/ContactInformation/*')
global with sharing class WSContactInformationManager{
    public class WSException extends Exception{
    }

    global class ContactInformation{
        public String firstName{ get; set; }

        public String lastName{ get; set; }

        public String product{ get; set; }

        public String homeCountry{ get; set; }

        public String atmFee{ get; set; }

        public String cardReplacementCost{ get; set; }

        public String costPerCalendarMonth{ get; set; }

        public ContactInformation(Contact contact, Cost_Per_Product__mdt costPerProduct){
            firstName = contact.FirstName;
            lastName = contact.LastName;
            product = costPerProduct.Product__c;
            homeCountry = costPerProduct.Home_Country__c;
            atmFee = String.valueOf(costPerProduct.ATM_Fee_in_other_currencies__c);
            cardReplacementCost = String.valueOf(costPerProduct.Card_Replacement_Cost__c);
            costPerCalendarMonth = String.valueOf(costPerProduct.Cost_Per_Calendar_Month__c);
        }

    }

    global class ContactWrapper{
        String firstName;
        String lastName;
        String product;
        String homeCountry;
        String externalReference;
    }

    @HttpGet
    global static void getContactByExtId(){
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        // Get the unique Id from the end of the URL
        String contactExtId = req.requestURI.substring(req.requestURI.lastIndexOf('/') + 1);

        try{
            // Get the contact
            Contact c;
            Contact[] contactList = [SELECT FirstName, LastName, Product__c, Home_Country__c
                           FROM Contact
                           WHERE External_Reference__c = :contactExtId];
            if (contactList.isEmpty()){
                WSException e = new WSException();
                e.setMessage(System.Label.WS_NORECORD);
                throw e;
            } else {
                c = contactList[0];
            }
            Cost_Per_Product__mdt cPP;

            // Check if the contact has a product and home country and get the cost per product
            if (c?.Product__c != null && c?.Home_Country__c != null){
                cPP = Cost_Per_Product__mdt.getInstance(c.Product__c + '_' + c.Home_Country__c);
                if (cPP == null){
                    WSException e = new WSException();
                    e.setMessage(System.Label.WS_NOPRODUCTINFO);
                    throw e;
                }
            } else{
                WSException e = new WSException();
                e.setMessage(System.Label.WS_CONTACTMISSINGINFO);
                throw e;
            }

            // Return the contact information
            res.responseBody = Blob.valueOf(JSON.serialize(new ContactInformation(c, cPP)));
            res.statusCode = 200;
        } catch (Exception e){
            System.debug('The following exception has occurred line : ' + e.getLineNumber());
            System.debug('The exception message is : ' + e.getMessage());
            System.debug('The stack trace is : ' + e.getStackTraceString());
            res.responseBody = Blob.valueOf(System.Label.WS_ERROR + ' : ' + e.getMessage());
            res.statusCode = 400;
        }
    }

    /**
     * @HttpPut - upsert
     * @param jsonString - JSON containing the list of contacts
     * @return void
     */
    @HttpPut
    global static void upsertContacts(){
        String requestBody = RestContext.request.requestBody.toString();
        RestResponse res = RestContext.response;
        try{
            List<Contact> contactsToUpsert = new List<Contact>();
            List<ContactWrapper> contactsWrappers = (List<ContactWrapper>)JSON.deserializeStrict(requestBody, List<ContactWrapper>.class);
            if (contactsWrappers.isEmpty()){
                WSException e = new WSException();
                e.setMessage(System.Label.WS_NOTHINGTOUPSERT);
                throw e;
            } else{
                // Find out if the contacts already exists
                Set<String> contactsExtIds = new Set<String>();
                for (ContactWrapper cw : contactsWrappers){
                    contactsExtIds.add(cw.externalReference);
                }
                Map<String, Contact> contactsMap = new Map<String, Contact>();
                for (Contact c : [SELECT Id, External_Reference__c
                                  FROM Contact
                                  WHERE External_Reference__c IN:contactsExtIds
                                  LIMIT 50000]){
                    contactsMap.put(c.External_Reference__c, c);
                }
                for (ContactWrapper cw : contactsWrappers){
                    Contact c = new Contact();
                    c.External_Reference__c = cw.externalReference;
                    c.FirstName = cw.firstName;
                    c.LastName = cw.lastName;
                    c.Product__c = cw.product;
                    c.Home_Country__c = cw.homeCountry;
                    c.Id = contactsMap.get(c.External_Reference__c)?.Id;
                    contactsToUpsert.add(c);
                }
            }
            if (!contactsToUpsert.isEmpty()){
                upsert contactsToUpsert;
                res.statusCode = 201;
                res.responseBody = Blob.valueOf(System.Label.WS_UPSERTSUCCESS + ' ' + contactsToUpsert.size() + ' ' + Schema.getGlobalDescribe().get('Contact').getDescribe().getLabelPlural());
            } else{
                WSException e = new WSException();
                e.setMessage(System.Label.WS_NOTHINGTOUPSERT);
                throw e;
            }
        } catch (Exception e){
            System.debug('The following exception has occurred line : ' + e.getLineNumber());
            System.debug('The exception message is : ' + e.getMessage());
            System.debug('The stack trace is : ' + e.getStackTraceString());
            res.responseBody = Blob.valueOf(System.Label.WS_ERROR + ' : ' + e.getMessage());
            res.statusCode = 400;
        }
    }

}