force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Tiers</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cost_Per_Product__mdt/Cost_Per_Product__mdt.object-meta.xml
<CustomObject>
    <description>Lists the cost per calendar month, ATM fee in other currencies and Card Replacement cost for each product and country</description>
    <label>Costs Per Product</label>
    <pluralLabel>Costs Per Products</pluralLabel>
</CustomObject>

force-app/main/default/objects/Cost_Per_Product__mdt/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
                <default>true</default>
                <label>DE</label>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cost_Per_Product__mdt/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Metal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Product_Tiers.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Standard</fullName>
        <default>true</default>
        <label>Standard</label>
    </customValue>
    <customValue>
        <fullName>Black</fullName>
    </customValue>
    <customValue>
        <fullName>Metal</fullName>
    </customValue>
    <masterLabel>Product Tiers</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Controller/DisplayProductInfoController.cls
public with sharing class DisplayProductInfoController{

    // Write a method comment
    /** 
     * Get the cost per product for the current case. Used in the lightning component displayProductInfo.
     * @param recordId Id of the case
     * @return Cost_Per_Product__mdt
     */
    @AuraEnabled(cacheable=true)
    public static Cost_Per_Product__mdt getCostPerProduct(String recordId){
        System.debug(recordId);
        Case currentCase = [SELECT Contact.Product__c, Contact.Home_country__c FROM Case WHERE Id = :Id.valueOf(recordId)];
        String product = currentCase.Contact.Product__c;
        String homeCountry = currentCase.Contact.Home_country__c;
        return Cost_Per_Product__mdt.getInstance(product + '_' + homeCountry);
    } 
    


}